### PR TITLE
Attachments

### PR DESCRIPTION
**Pull request by chrishaid**
Hi Gastrograph team --

It's me again.  I just implemented attachments functionality to RMandrill. 

Let me know if there is anything you'd like to change or make clearer.

### CODE REVIEW

**Comment by chrishaid** [comment]
@moosilauke18 @JasonCEC Any chance you all would be willing to merge this pull request.  It simply adds attachment functionality to the package.  I've got my fork in production but since Gastrograph started this package I'd rather point people towards this repo rather than my own.

**Comment by moosilauke18** [comment]
Sorry for the taking a bit to look over it.

**Comment by JasonCEC** [comment]
Hey Chris,

Thanks for all the work you've been putting into this!

If I remember correctly,
there was a set of pull requests you issued a few months back,
but then later decided to revert - is that right?

Whatever happened with those,
and what could we do to help get that functionality into this package?

Cheers!
- Jason

On Thu, Oct 8, 2015 at 7:07 PM, Chris Haid notifications@github.com wrote:

> Hi Gastrograph team --
> 
> It's me again. I just implemented attachments functionality to RMandrill.
> 
> ## Let me know if there is anything you'd like to change or make clearer.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/Gastrograph/RMandrill/pull/4
> Commit Summary
> - added .gitgnore .RBuildignore
> - Added process_attachments helper function.
> - Completed attachments functionality. Added documentation for
>   process_attachments. Updated other docs and NAMESPACE.
> 
> File Changes
> - _M_ .Rbuildignore
>   https://github.com/Gastrograph/RMandrill/pull/4/files#diff-0 (2)
> - _A_ .gitignore
>   https://github.com/Gastrograph/RMandrill/pull/4/files#diff-1 (4)
> - _M_ DESCRIPTION
>   https://github.com/Gastrograph/RMandrill/pull/4/files#diff-2 (3)
> - _M_ NAMESPACE
>   https://github.com/Gastrograph/RMandrill/pull/4/files#diff-3 (2)
> - _M_ R/helper_utilities.R
>   https://github.com/Gastrograph/RMandrill/pull/4/files#diff-4 (88)
> - _M_ R/send.R
>   https://github.com/Gastrograph/RMandrill/pull/4/files#diff-5 (90)
> - _M_ man/RMandrill.Rd
>   https://github.com/Gastrograph/RMandrill/pull/4/files#diff-6 (2)
> - _M_ man/mandrill_send_template.Rd
>   https://github.com/Gastrograph/RMandrill/pull/4/files#diff-7 (8)
> - _A_ man/process_attachements.Rd
>   https://github.com/Gastrograph/RMandrill/pull/4/files#diff-8 (19)
> - _M_ man/process_contents.Rd
>   https://github.com/Gastrograph/RMandrill/pull/4/files#diff-9 (2)
> - _M_ man/process_images.Rd
>   https://github.com/Gastrograph/RMandrill/pull/4/files#diff-10 (2)
> 
> Patch Links:
> - https://github.com/Gastrograph/RMandrill/pull/4.patch
> - https://github.com/Gastrograph/RMandrill/pull/4.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Gastrograph/RMandrill/pull/4.

## 

Founder & Chief Executive Officer
Analytical Flavor Systems, LLC.

Mobile: (305) 794 - 8392
www.Gastrograph.com
www.CultofQuality.com http://www.cultofquality.com/

Founder & Former Executive Director of The Tea Institute at Penn State
http://sites.psu.edu/teainstitute/
-    "Life is what happens while you're making other plans,*
-    & the only true acts of free will are love and disobedience"*

Read our story on the NVIDIA blog:
http://blogs.nvidia.com/blog/2015/09/02/beer/

All materials confidential.
If you are not the intended recipient, do not read (too late?), copy or
distribute this e-mail or any attachments.Instead, please notify the sender
and delete the e-mail and any attachments. Thank you.
Copyright © Analytical Flavor Systems 2015

**Comment by chrishaid** [comment]
Hi Jason--

Thanks for taking a look.  You all did a code review and had me fix some linting and move some functionality into a separate function.  After doing that you merged the pull request.  So everything is still in the master branch now (that was for the the embedded images feature).

The attachments feature very closely mirrors the images functionality.  After reviewing let me know if there is anything you'd like me to change.

Oh, FWIW, I'm running RMandrill in production right now with the attachments and so far so good. 

c

**Pull request merged**
